### ISSUE TITLE
How to add comments from java codebase that exists at class variable and function level

### ISSUE THREAD

**Issue by JayGhiya** [phodal/chapi#25]
Is there a roadmap to modify existing code container to add that sry not a kotlin person otherwise would have contributed

**Comment by phodal** [comment]
in current design, the `Content` field is for full function code which with comments, you maybe try this. Then parse it in your code.

for class level:

https://github.com/phodal/chapi/blob/39562227fda0cc7ae66fa767ccbdf99843108cba/chapi-domain/src/main/kotlin/chapi/domain/core/CodeDataStruct.kt#L66

for function level:

https://github.com/phodal/chapi/blob/39562227fda0cc7ae66fa767ccbdf99843108cba/chapi-domain/src/main/kotlin/chapi/domain/core/CodeFunction.kt#L47

**Comment by phodal** [comment]
Here is a example： https://github.com/unit-mesh/unit-gen/blob/master/code-quality/src/main/kotlin/cc/unitmesh/quality/comment/CodeComment.kt

**Comment by JayGhiya** [comment]
hey @phodal this is great so the spec covers the comments . so i just did parsing for example class and functions with comments. looks like content at codeFunction and CodeDataStruct does not autofill content as of now. Is this already on roadmap to do the same?

**Comment by phodal** [comment]
Not sure about javaparser, the design princinple of Chapi is to support multi-languages, like: https://github.com/archguard/archguard/tree/master/analyser_sourcecode

Here is othr example to fill with content:

https://github.com/archguard/archguard/blob/049f3cc8f2c0e2c34e65bb0049f645caa5be9bf8/analyser_sourcecode/lang_java/src/main/kotlin/org/archguard/scanner/analyser/JavaAnalyser.kt#L45-L56
